---
title: "Dynam jobevolutie kaartjes"
output: 
  html_notebook: 
    code_folding: show
    theme: lumen
---

```{r, message=FALSE, warning=FALSE}
library(here)
library(readxl)
library(dplyr)
library(BelgiumMaps.StatBel)
library(sf)
library(tmap)
library(leaflet)
library(leaflet.minicharts)
library(htmltools)
library(ggplot2)
library(stringr)
```

```{r}
dynam.prov = read_excel(
    '20180425_dynam_be_jobdata_origineel.xlsx', 'Sheet2',
    skip = 1,  col_names = c(
      'province_lbl', 'province_nis_code', 
      'absoluut_bruto_toename', 'absoluut_bruto_afname', 'absoluut_netto', 'delme',
      'delmetoo', 'bruto_toename_pct', 'bruto_afname_pct', 'netto_pct')) %>%
  select(-delme, -delmetoo)
```

```{r}
dynam.prov
```

```{r, warning=FALSE, message=FALSE}
dynam.prov  <- dynam.prov %>% 
  mutate(
    province_lbl = case_when(
      province_lbl == 'Brussels Hoofdstedelijk Gewest' ~ 'Brussel',
      TRUE ~ province_lbl))

dynam.prov = dynam.prov %>%
  mutate(
    province_lbl_pct = str_c(province_lbl, '    ', str_sub(as.character(netto_pct*100),1,4), '%'))

province_lbl_ordered <- dynam.prov %>%
  arrange(netto_pct) %>% # rangschik procentuele of absolute groei
  # arrange(absoluut_netto) %>%
  pull(province_lbl_pct)

    
dynam.prov = dynam.prov %>%
    mutate(province_lbl_pct = factor(province_lbl_pct, levels = province_lbl_ordered))


```

```{r, fig.width=8, fig.height=6, fig.align='center'}
# Overlapping barcharts:
# http://stephanieevergreen.com/overlapping-bars/
# https://gist.github.com/hrbrmstr/035f998517de2384e9962cff7df874bd
# 

gg <- ggplot(data=dynam.prov, aes(y=province_lbl_pct, yend=province_lbl_pct))
gg <- gg + geom_segment(aes(x=absoluut_bruto_afname, xend=0, color="Jobverlies"), size=10)
gg <- gg + geom_segment(aes(x=absoluut_bruto_toename, xend=0, color="Jobgroei"), size=5)
gg <- gg + scale_x_continuous(labels=function(x) format(x, decimal.mark = ',', big.mark = ".", scientific = FALSE))
gg <- gg + scale_color_manual(name=NULL, values=c(Jobverlies="#bebebf", Jobgroei="#1074bc"))
gg <- gg + guides(color=guide_legend(keywidth=0, override.aes=list(size=4)))
gg <- gg + labs(
  x=NULL, y=NULL,
  title="Alle provincies kennen een netto jobaangroei, met de grootste\nprocentuele groei in Namen",
  subtitle = 'Procentuele en absolute jobevolutie per provincie, 2016-2017',
  caption="Bron: HIVA-KU Leuven | DynaM | dynamresearch.be")
gg <- gg + theme_minimal()
gg <- gg + theme(axis.text.x=element_text(margin=margin(t=0)))
gg <- gg + theme(axis.text.y=element_text(margin=margin(r=-10)))
gg <- gg + theme(panel.grid.minor=element_blank())
gg <- gg + theme(panel.grid.major.y=element_blank())
gg <- gg + theme(plot.title=element_text(face="bold"))
gg <- gg + theme(plot.margin=margin(20,20,20,20))
gg <- gg + theme(plot.caption=element_text(size=8, margin=margin(t=10, r=0)))
gg <- gg + theme(legend.position=c(0.8, 0.9))
gg <- gg + theme(legend.direction="vertical")
gg <- gg + theme(legend.background=element_rect(fill="white", color="white"))
gg
```


```{r, warning=FALSE}
dynam.prov = dynam.prov %>%
  mutate(
    netto_pct = netto_pct*100,
    absoluut_bruto_afname = absoluut_bruto_afname*-1)
```

```{r}
data('BE_ADMIN_PROVINCE') 
data("BE_ADMIN_REGION")

# convert to simple features dataset-structure
provinces = st_as_sf(BE_ADMIN_PROVINCE) 
regions = st_as_sf(BE_ADMIN_REGION) 

# Spatial object for Brussels-region is not included in provences, add from region
provinces = rbind(
  provinces %>% select(CD_PROV_REFNIS, TX_PROV_DESCR_NL),
  regions %>%
    filter(TX_RGN_DESCR_NL == "Brussels Hoofdstedelijk Gewest") %>%
    mutate(CD_RGN_REFNIS = '04000') %>%
    select(
      CD_PROV_REFNIS = CD_RGN_REFNIS,
      TX_PROV_DESCR_NL = TX_RGN_DESCR_NL))
```

```{r}
provinces = provinces %>%
  mutate(CD_PROV_REFNIS = as.character(CD_PROV_REFNIS)) %>%
  left_join(dynam.prov, c('CD_PROV_REFNIS' = 'province_nis_code'))
```


```{r}
pal <- colorBin("Greens", domain = dynam.prov$netto_pct)
```

```{r, warning=FALSE}
# get centroid coordinates for each province to plot barchart there
provinces_coords = st_coordinates(st_centroid(provinces))
```

```{r}
d.abs = dynam.prov %>%
  select(
    'Jobgroei' = absoluut_bruto_toename,
    'Jobverlies' = absoluut_bruto_afname,
    'Netto jobevolutie' = absoluut_netto)
```


```{r results="asis", echo=FALSE}
cat("
<style>
.leaflet-container {
    background: #FFF;
}
</style>
")
```

```{r}
m.prov = leaflet(provinces, width = '100%') %>% 
  # add grey arrondissement polygons w/t white border
  addPolygons(
    weight = 2,
    opacity = 1,
    dashArray = "3",
    fillColor = ~pal(netto_pct), color = 'white') %>% 
  addLegend(pal = pal, values = ~absoluut_netto, opacity = 0.7,
            title = 'Netto jobevolutie (%)',
  position = "bottomright")

colors <- c("#7cae00", "#f8766d", "#c77cff")
m.prov = m.prov %>%
  addMinicharts(
    provinces_coords[,1], provinces_coords[,2],
    chartdata = d.abs,
    colorPalette = colors,
    width = 45, height = 45)

map_title <- tags$div(
   HTML('<b>Bruto en netto jobevolutie per provincie, 2017-2018 (<a href="https://dynamresearch.be/">DynaM</a>)</b>')
 )  

m.prov = m.prov %>% 
  addControl(map_title, position = "bottomleft")

m.prov

```

